#!/bin/bash  
rm -r resources/WebApps
git add -A  
read -p "Commit description: " desc  
git commit -m "$desc"  
git push github master
mkdir resources/WebApps
cp ../../WebApps/*.html resources/WebApps
mkdir resources/WebApps/js
mkdir resources/WebApps/lib
cp -r ../../WebApps/js resources/WebApps/js
cp -r ../../WebApps/lib resources/WebApps/lib
git add -A  
git commit -m "$desc"
git push origin master
