#!/bin/bash  
rm -r resources/WebApps
git add -A  
read -p "Commit description: " desc  
git commit -m "$desc"  
git push github master
cp -r ../../WebApps resources
git add -A  
git commit -m "$desc"  
git push origin master
