var TEST=!0,DEBUG=!1,CreJs=CreJs||{};window.CreJs=CreJs;CreJs.Creanvas=CreJs.Creanvas||{};CreJs.Creanvas=CreJs.Creanvas;CreJs.Creanvas.ElementDecorators=CreJs.Creanvas.ElementDecorators||{};CreJs.Creanvas.ElementDecorators=CreJs.Creanvas.ElementDecorators;CreJs.Crelog=CreJs.Crelog||{};CreJs.Crelog=CreJs.Crelog;CreJs.Creevents=CreJs.Creevents||{};CreJs.Creevents=CreJs.Creevents;CreJs.CreHelpers=CreJs.CreHelpers||{};CreJs.CreHelpers=CreJs.CreHelpers;CreJs=CreJs||{};
(function(){var a=CreJs.Core=CreJs.Core||{};a.Vector=function(c,d,f){var e=this;this.x=c;this.y=d;this.z=f||0;this.draw=function(b,a,c,k){b.lineWidth=5;b.strokeStyle=k;b.beginPath();b.moveTo(a,c);b.lineTo(a+100*e.x,c+100*e.y);b.stroke();b.lineWidth=1;b.strokeStyle="#000"};this.getCoordinates=function(b){return{u:a.scalarProduct(e,b.u),v:a.scalarProduct(e,b.v),w:a.scalarProduct(e,b.w)}};this.setCoordinates=function(b,a,c,k){k=k||0;e.x=a*b.u.x+c*b.v.x+k*b.w.x;e.y=a*b.u.y+c*b.v.y+k*b.w.y;e.z=a*b.u.z+
c*b.v.z+k*b.w.z}};a.getUnitVectors=function(c,d,f,e){c=f-c;d=e-d;e=Math.sqrt(c*c+d*d);return{u:new a.Vector(c/e,d/e),v:new a.Vector(-d/e,c/e),w:0}};a.drawUnitVectors=function(a,d,f,e,b){a.lineWidth=5;a.strokeStyle=b;a.beginPath();a.moveTo(d,f);a.lineTo(d+100*e.u.x,f+100*e.u.y);a.moveTo(d,f);a.lineTo(d+50*e.v.x,f+50*e.v.y);a.stroke();a.lineWidth=1;a.strokeStyle="#000"};a.drawCoordinateVector=function(a,d,f,e,b,g,h){a.lineWidth=5;a.strokeStyle=h;a.beginPath();a.moveTo(d,f);a.lineTo(d+100*b*e.u.x,f+
100*b*e.u.y);a.lineTo(d+100*b*e.u.x+100*g*e.v.x,f+100*b*e.u.y+100*g*e.v.y);a.stroke();a.lineWidth=1;a.strokeStyle="#000"};a.scalarProduct=function(a,d){return a.x*d.x+a.y*d.y};a.VectorProduct=function(c,d){return new a.Vector(c.y*d.z-c.z*d.y,c.z*d.x-c.x*d.z,c.x*d.y-c.y*d.x)}})();if(TEST){var CreJsTest=CreJsTest||{};(function(){(CreJsTest.Core=CreJs.Core||{}).test_Vector_constructor=function(){var a=new CreJs.Core.Vector(1,2,3);return 1!=a.x?"FAILED! vector.x: Expected 1, was "+a.x:2!=a.y?"FAILED! vector.y: Expected 2, was "+a.y:3!=a.z?"FAILED! vector.z: Expected 3, was "+a.z:"OK"}})()};CreJs=CreJs||{};
(function(){CreJs.Creanvas=CreJs.Creanvas||{};CreJs.Creanvas.CollisionSolver=function(a){var c=function(a,b){var c,d,k,l,n,f,m;l=a.getClientRect();n=b.getClientRect();c=Math.max(l.left,n.left)-1;d=Math.min(l.right,n.right)+1;k=Math.max(l.top,n.top)-1;l=Math.min(l.bottom,n.bottom)+1;if(!(0>=d-c||0>=l-k)){c=a.collisionContext.getImageData(0,0,a.width,a.height);a.collisionContext.scale(1/(a.scaleX||1),1/(a.scaleY||1));a.collisionContext.rotate(-(a.angle||0));a.collisionContext.translate(b.x-a.x,b.y-
a.y);a.collisionContext.rotate(b.angle||0);a.collisionContext.scale(b.scaleX||1,b.scaleY||1);a.collisionContext.globalCompositeOperation="destination-out";a.collisionContext.drawImage(b.collidedContext.canvas,0,0,b.width,b.height,-b.dx,-b.dy,b.width,b.height);a.collisionContext.scale(1/(b.scaleX||1),1/(b.scaleY||1));a.collisionContext.rotate(-b.angle||0);a.collisionContext.translate(-b.x+a.x,-b.y+a.y);a.collisionContext.rotate(a.angle||0);a.collisionContext.scale(a.scaleX||1,a.scaleY||1);f=a.collisionContext.getImageData(0,
0,a.width,a.height);a.collisionContext.globalCompositeOperation="source-over";a.collisionContext.putImageData(c,0,0);m=[];a.edges.forEach(function(b){90>f.data[b.y*a.width*4+4*b.x+3]&&m.push(b)});if(2>m.length)return null;var p;k=d=0;c=m.length-1;for(l=1;l<m.length;l++)for(n=l+1;n<m.length;n++){p=m[l].x-m[n].x;var q=m[l].y-m[n].y;p=Math.sqrt(p*p+q*q);p>d&&(d=p,k=l,c=n)}d=a.getCanvasXY(m[k].x-a.dx,m[k].y-a.dy);c=a.getCanvasXY(m[c].x-a.dx,m[c].y-a.dy);return d.x==c.x&&d.y==c.y?null:{x:Math.round((d.x+
c.x)/2),y:Math.round((d.y+c.y)/2),vectors:CreJs.Core.getUnitVectors(d.x,d.y,c.x,c.y)}}},d=function(a,b,c){var d,k,l,n,f,m;d=c.vectors;n=new CreJs.Core.Vector(c.x-a.x,c.y-a.y);f=CreJs.Core.VectorProduct(n,d.v).z;m=new CreJs.Core.Vector(c.x-b.x,c.y-b.y);c=CreJs.Core.VectorProduct(m,d.v).z;var p=CreJs.Core.VectorProduct(n,d.v),q=CreJs.Core.VectorProduct(m,d.v);k=new CreJs.Core.Vector(a.moving.speed.x,a.moving.speed.y);l=new CreJs.Core.Vector(b.moving.speed.x,b.moving.speed.y);a.scaleSpeed&&(k.x+=n.x*
a.scaleSpeed.x,k.y+=n.y*a.scaleSpeed.y);b.scaleSpeed&&(l.x+=m.x*b.scaleSpeed.x,l.y+=m.y*b.scaleSpeed.y);n=k.getCoordinates(d);l=l.getCoordinates(d);p=a.collidable.coefficient*b.collidable.coefficient*2*(l.v-n.v+b.moving.rotationSpeed*q.z-a.moving.rotationSpeed*p.z)/(1/b.m+1/a.m+q.z*q.z/b.getM()+p.z*p.z/a.getM());a.moving.speed.x+=p/a.m*d.v.x;a.moving.speed.y+=p/a.m*d.v.y;b.moving.speed.x-=p/b.m*d.v.x;b.moving.speed.y-=p/b.m*d.v.y;a.moving.rotationSpeed+=p*f/a.getM();b.moving.rotationSpeed-=p*c/b.getM()},
f=function(){return a.elements.filter(function(a){return a.collidable})};this.solveCollision=function(a){var b=f(),g,h,k;g=a.getCenter();b=b.filter(function(b){var c;if(b.id===a.id||!(b.moving.speed.x||b.moving.speed.y||a.moving.speed.x||a.moving.speed.y||b.scaleSpeed||a.scaleSpeed))return!1;c=b.getCenter();return Math.sqrt((g.x-c.x)*(g.x-c.x)+(g.y-c.y)*(g.y-c.y))>a.getRadius()+b.getRadius()?!1:!0});if(0==b.length)return!0;h=null;b.forEach(function(b){h||(h=c(a,b))&&(k=b)});if(!h)return!0;d(a,k,h);
a.events.dispatch("collision",{element:k,collisionPoint:h});k.events.dispatch("collision",{element:a,collisionPoint:h});return!1}}})();CreJs=CreJs||{};
(function(){CreJs.Creanvas=CreJs.Creanvas||{};CreJs.Creanvas.Controller=function(a){var c,d,f,e,b,g,h;e=this;c=a.canvas;h=a.timeScale||1;a.realTime?(g=Date.now(),this.getTime=function(){return(Date.now()-g)*h}):(b=0,setInterval(function(){b+=10*h},10),this.getTime=function(){return b});this.log=function(b){a.log&&a.log(b)};this.log("Starting controller");e.context=c.getContext("2d");d=!0;isDrawing=!1;f=a.refreshTime||50;this.triggerPointedElementEvent=function(a,b){var c=!1;e.elements.filter(function(b){return b.canHandle(a)}).sort(function(a,b){return b.z||
0-a.z||0}).forEach(function(d){!c&&d.hit(b.x,b.y)&&(d.events.dispatch(a,b),c=!0)})};this.triggerElementEventByIdentifier=function(a,b){e.elements.forEach(function(c){c.touchIdentifier==b.touchIdentifier&&c.events.dispatch(a,b)})};this.registerCanvasPointerEvent=function(a,b){c.addEventListener(a,function(c){setTimeout(function(){var d=function(c,d){e.log("Canvas event "+a+" with touchIdentifier "+d);var g=e.getCanvasXYFromClientXY(c);g.touchIdentifier=d;e.triggerPointedElementEvent(b,g)};if(c.changedTouches)for(var g=
0;g<c.changedTouches.length;g++)d(c.changedTouches[g],c.changedTouches[g].identifier);else d(c,-1)})})};this.registerTouchIdentifierEvent=function(a,b){c.addEventListener(a,function(c){setTimeout(function(){var d=function(c,d){e.log("Canvas event "+a+" with touchIdentifier "+d);var g=e.getCanvasXYFromClientXY(c);g.touchIdentifier=d;e.triggerElementEventByIdentifier(b,g)};if(c.changedTouches)for(var g=0;g<c.changedTouches.length;g++)d(c.changedTouches[g],c.changedTouches[g].identifier);else d(c,-1)})})};
this.events=new CreJs.Creevents.EventContainer;this.registerCanvasPointerEvent("click","click");this.registerCanvasPointerEvent("mousedown","pointerDown");this.registerCanvasPointerEvent("touchstart","pointerDown");this.registerTouchIdentifierEvent("mousemove","pointerMove");this.registerTouchIdentifierEvent("touchmove","pointerMove");this.registerTouchIdentifierEvent("mouseup","pointerUp");this.registerTouchIdentifierEvent("touchend","pointerUp");this.stop=function(){e.events.dispatch("deactivate");
e.elements=[]};this.redraw=function(){d=!0};this.getCanvasXYFromClientXY=function(a){var b=c.getBoundingClientRect();return{x:Math.round((a.clientX-b.left)*c.width/b.width),y:Math.round((a.clientY-b.top)*c.height/b.height)}};e.elements=[];this.addElement=function(a){a.controller=e;a=new CreJs.Creanvas.Element(a);e.elements.push(a);return a};this.addElement({name:"background",width:c.width,height:c.height,translate:{dx:0,dy:0},draw:a.drawBackground||function(b){b.fillStyle=a.backgroundStyle||"#FFF";
b.fillRect(0,0,this.width,this.height)},z:-Infinity});setInterval(function(){d&&!isDrawing&&(isDrawing=!0,e.elements.sort(function(a,b){return(a.z||0)-(b.z||0)}).forEach(function(a){e.context.translate(a.x,a.y);e.context.rotate(a.angle||0);e.context.scale(a.scaleX||1,a.scaleY||1);e.context.drawImage(a.temporaryRenderingContext.canvas,0,0,a.width,a.height,-a.dx,-a.dy,a.width,a.height);e.context.scale(1/(a.scaleX||1),1/a.scaleY||1);e.context.rotate(-(a.angle||0));e.context.translate(-a.x,-a.y)}),isDrawing=
!1)},f)}})();CreJs=CreJs||{};
(function(){var a=CreJs.Creanvas=CreJs.Creanvas||{};a.Element=function(c){if(c.hasOwnProperty("controller")&&c.hasOwnProperty("draw")){var d=[];this.controller=c.controller;this.x=c.x||0;this.y=c.y||0;this.z=c.z||0;this.id=CreJs.CreHelpers.GetGuid();this.name=c.name;this.width=c.width;this.height=c.height;this.angle=c.angle||0;this.scaleX=c.scaleX||1;this.scaleY=c.scaleY||1;this.m=1;var f=c.draw,e=c.translate||{dx:c.width/2,dy:c.height/2};this.dx=e.dx;this.dy=e.dy;c.image?this.image=c.image:(e=this.controller.context.canvas.ownerDocument.createElement("canvas"),
e.width=c.width,e.height=c.height,this.temporaryRenderingContext=e.getContext("2d"),this.temporaryRenderingContext.beginPath(),this.temporaryRenderingContext.translate(this.dx,this.dy),c.draw(this.temporaryRenderingContext),this.image=this.temporaryRenderingContext.getImageData(0,0,c.width,c.height));this.getM=function(){return b.m/12*(b.width*b.scaleX*b.width*b.scaleX+b.height*b.scaleY*b.height*b.scaleY)};this.geRadiusCache=function(){return Math.sqrt(b.width*b.width*b.scaleX*b.scaleX+b.height*b.height*
b.scaleY*b.scaleY)/2};this.getRadius=function(){var a=b.width+""+b.height+""+b.scaleX+""+b.scaleY;if(d.getRadius&&d.getRadius.key==a)return d.getRadius.value;var c=b.geRadiusCache();d.geRadius={key:a,value:c};return c};var b=this;c.rules&&(b.rules=[],c.rules.forEach(function(a){var c=b.rules.length;b.rules.push(a);setInterval(function(){b.rules[c].rule.call(b);b.triggerRedraw()},a.checkTime)}));this.events=new CreJs.Creevents.EventContainer;this.isPointInPath=function(a){a=b.controller.getCanvasXYFromClientXY(a);
return b.controller.noDrawContext.isPointInPath(b,f,a)};if(CreJs.Creanvas.elementDecorators)for(e=0;e<a.elementDecorators.length;e++){var g=CreJs.Creanvas.elementDecorators[e];c.hasOwnProperty(g.type)&&c[g.type]&&g.applyTo(b,c[g.type])}this.hit=function(a,c){var d=Math.round(a-b.x+b.dx),e=Math.round(c-b.y+b.dy);return 0<=d&&d<=b.width&&0<=e&&e<=b.height&&0<b.image.data[4*e*b.width+4*d+3]};this.clone=function(){c.image=b.image;return b.controller.addElement(c)};this.applyDecorator=function(a,c){a.applyTo(b,
c)};this.removeDecorator=function(a){b.events.removeEventListener({eventGroupType:a,listenerId:b.id})};this.canHandle=function(a){return"click"==a||"pointerDown"==a||b.events.hasEvent(a)};this.deactivate=function(){b.controller.events.removeEventListener({listenerId:b.id});b.temporaryRenderingContext=null};b.controller.events.addEventListener({eventId:"deactivate",listenerId:b.id,handleEvent:function(a){b.deactivate()}});this.triggerRedraw=function(){b.controller.redraw()};this.getCanvasXY=function(a,
c){return{x:Math.round(b.x+a*b.scaleX*Math.cos(b.angle)-c*b.scaleY*Math.sin(b.angle)),y:Math.round(b.y+a*b.scaleX*Math.sin(b.angle)+c*b.scaleY*Math.cos(b.angle))}};this.getCanvasXYNoRounding=function(a,c){return{x:b.x+a*b.scaleX*Math.cos(b.angle)-c*b.scaleY*Math.sin(b.angle),y:b.y+a*b.scaleX*Math.sin(b.angle)+c*b.scaleY*Math.cos(b.angle)}};this.getElementXY=function(a,c){return{x:Math.round(((a-b.x)*Math.cos(b.angle)+(c-b.y)*Math.sin(b.angle))/b.scaleX),y:Math.round(((c-b.y)*Math.cos(b.angle)-(a-
b.x)*Math.sin(b.angle))/b.scaleY)}};this.getCenter=function(){return b.getCanvasXY(-b.dx+b.width/2,-b.dy+b.height/2)};var h=[];h.push({x:-b.dx,y:-b.dy});h.push({x:-b.dx+b.width,y:-b.dy});h.push({x:-b.dx+b.width,y:-b.dy+b.height});h.push({x:-b.dx,y:-b.dy+b.height});this.getClientCornersCache=function(){return h.map(function(a){return b.getCanvasXY(a.x,a.y)})};this.getClientCorners=function(){var a=b.x+""+b.y+""+b.angle+""+b.scaleX+""+b.scaleX;if(d.getClientCorners&&d.getClientCorners.key==a)return d.getClientCorners.value;
var c=b.getClientCornersCache();d.getClientCorners={key:a,value:c};return c};this.getClientRectCache=function(){var a=b.getClientCorners();return{top:a.reduce(function(a,b){return Math.min(a,b.y)},Infinity),bottom:a.reduce(function(a,b){return Math.max(a,b.y)},-Infinity),left:a.reduce(function(a,b){return Math.min(a,b.x)},Infinity),right:a.reduce(function(a,b){return Math.max(a,b.x)},-Infinity)}};this.getClientRect=function(){var a=b.x+""+b.y+""+b.angle+""+b.scaleX+""+b.scaleX;if(d.getClientRect&&
d.getClientRect.key==a)return d.getClientRect.value;var c=b.getClientRectCache();d.getClientRect={key:a,value:c};return c}}}})();CreJs=CreJs||{};(function(){CreJs.Creanvas=CreJs.Creanvas||{};CreJs.Creanvas.elementDecorators=CreJs.Creanvas.elementDecorators||[];CreJs.Creanvas.elementDecorators.push({type:"clickable",applyTo:function(a,c){a.onClick=function(d){c.onclick.call(a,d);a.triggerRedraw()};a.events.addEventListener({eventId:"click",handleEvent:a.onClick})}})})();CreJs=CreJs||{};
(function(){CreJs.Creanvas=CreJs.Creanvas||{};CreJs.Creanvas.elementDecorators=CreJs.Creanvas.elementDecorators||[];CreJs.Creanvas.elementDecorators.push({type:"collidable",applyTo:function(a,c){a.collidable={};a.controller.collisionSolver=a.controller.collisionSolver||new CreJs.Creanvas.CollisionSolver(a.controller);c.hasOwnProperty("collisionCoefficient")?a.collidable.coefficient=c.collisionCoefficient:a.collidable.coefficient=1;a.moving=a.moving||{speed:new CreJs.Core.Vector(0,0),acceleration:new CreJs.Core.Vector(0,
0),rotationSpeed:0};a.events.addEventListener({eventId:"collision",handleEvent:function(b){c.onCollision&&c.onCollision.call(a,b)}});a.preMove=this.preMove||[];a.preMove.push(function(){return a.controller.collisionSolver.solveCollision(a)});var d=a.controller.context.canvas,f=d.ownerDocument.createElement("canvas"),d=d.ownerDocument.createElement("canvas");f.width=d.width=a.width;f.height=d.height=a.height;a.collidedContext=d.getContext("2d");a.collidedContext.putImageData(a.image,0,0);a.collidedContext.globalCompositeOperation=
"source-atop";a.collidedContext.fillStyle="#000";a.collidedContext.fillRect(0,0,a.width,a.height);a.collisionContext=f.getContext("2d");a.collisionContext.globalCompositeOperation="source-over";a.collisionContext.drawImage(a.collidedContext.canvas,0,0);f=a.collisionContext.getImageData(0,0,a.width,a.height);d=a.collisionContext.createImageData(a.width,a.height);a.edges=[];for(var e=0;e<a.width;e++)for(var b=0;b<a.height;b++)if(!(200>f.data[b*a.width*4+4*e+3])){for(var g=!1,h=-1;2>h;h++)for(var k=
-1;2>k;k++)if(0>b+h||0>e+k||b+h>a.height-1||e+h>a.width-1||100>f.data[(b+h)*a.width*4+4*(e+k)+3])g=!0,k=h=2;a.collisionContext.putImageData(d,0,0);g&&(a.edges.push({x:e,y:b}),d.data[b*a.width*4+4*e]=0,d.data[b*a.width*4+4*e+1]=0,d.data[b*a.width*4+4*e+2]=0,d.data[b*a.width*4+4*e+3]=255)}a.collisionContext.putImageData(d,0,0);a.collisionContext.translate(a.dx,a.dy)}})})();CreJs=CreJs||{};(function(){CreJs.Creanvas=CreJs.Creanvas||{};CreJs.Creanvas.elementDecorators=CreJs.Creanvas.elementDecorators||[];CreJs.Creanvas.elementDecorators.push({type:"droppable",applyTo:function(a,c){a.isDroppable=!0;a.dropZone=c.dropZone;a.controller.log("Now droppable: "+a.id)}})})();CreJs=CreJs||{};
(function(){CreJs.Creanvas=CreJs.Creanvas||{};CreJs.Creanvas.elementDecorators=CreJs.Creanvas.elementDecorators||[];CreJs.Creanvas.elementDecorators.push({type:"dropzone",applyTo:function(a,c){var d=c.availableSpots,f=c.dropX,e=c.dropY;a.droppedElements=[];a.events.addEventListener({eventGroupType:"dropzone",eventId:"drop",handleEvent:function(b){0>=d||(a.controller.log("drop event on dropzone "+a.id+", dropped "+b.droppedElement.id),d--,b.droppedElement.x=f||a.x,b.droppedElement.y=e||a.y,b.droppedElement.dropZone=
a,a.droppedElements.push(b.droppedElement),b.droppedElement.events.dispatch("dropped",{dropZone:a,droppedElement:b.droppedElement}),a.events.dispatch("droppedIn",{dropZone:a,droppedElement:b.droppedElement}),a.triggerRedraw())},listenerId:a.id});a.drag=function(b){a.controller.log("dragging from dropzone "+a.id+", dragged "+b.id);b.dropZone=null;d++;a.droppedElements.splice(a.droppedElements.indexOf(b),1);a.triggerRedraw()}}})})();CreJs=CreJs||{};
(function(){CreJs.Creanvas=CreJs.Creanvas||{};CreJs.Creanvas.elementDecorators=CreJs.Creanvas.elementDecorators||[];CreJs.Creanvas.elementDecorators.push({type:"duplicable",applyTo:function(a,c){var d=c.isBlocked,f=c.hasOwnProperty("generatorCount")?c.generatorCount:Infinity,e=!1;a.events.addEventListener({eventGroupType:"duplicable",eventId:"pointerDown",handleEvent:function(b){0<=b.touchIdentifier&&(e=!0);if(!(e&&0>b.touchIdentifier||d&&d()||0>=f)){a.controller.log("pointereDown event on duplicable "+a.id+
", count id  "+f);f--;var g=a.clone();g.name+=" (duplicate)";g.removeDecorator("duplicable");g.applyDecorator(CreJs.Creanvas.getElementDecorator("movable"),{isBlocked:c.isBlocked});g.startMoving(b);a.triggerRedraw()}},listenerId:a.id})}})})();CreJs=CreJs||{};(function(){CreJs.Creanvas=CreJs.Creanvas||{};CreJs.Creanvas.elementDecorators=CreJs.Creanvas.elementDecorators||[];CreJs.Creanvas.getElementDecorator=function(a){var c=CreJs.Creanvas.elementDecorators.filter(function(c){return c.type==a});return 0==c.length?null:c[0]}})();CreJs=CreJs||{};
(function(){CreJs.Creanvas=CreJs.Creanvas||{};CreJs.Creanvas.elementDecorators=CreJs.Creanvas.elementDecorators||[];CreJs.Creanvas.elementDecorators.push({type:"movable",applyTo:function(a,c){var d=!1,f=this.touchIdentifier=null,e=c.isBlocked;a.startMoving=function(b){a.controller.log("Starting moving - identifier: "+b.touchIdentifier);d=!0;a.touchIdentifier=b.touchIdentifier;f={x:b.x,y:b.y};a.dropZone&&(a.dropZone.drag(a),a.dropZone=null)};a.moveCompleted=function(b){a.controller.log("Completed move - identifier: "+b.touchIdentifier);
d=!1;f=null;a.isDroppable&&(a.controller.log("Trigger drop - identifier: "+b.touchIdentifier),a.controller.triggerPointedElementEvent("drop",{x:b.x,y:b.y,droppedElement:a}))};a.events.addEventListener({eventGroupType:"movable",eventId:"pointerDown",handleEvent:function(b){e&&e()||a.startMoving(b)},listenerId:a.id});var b=!1;a.events.addEventListener({eventGroupType:"movable",eventId:"pointerMove",handleEvent:function(c){!d||e&&e()||(b||(b=!0,a.controller.log("pointereMove event on movable "+a.id+
" ("+a.touchIdentifier+")")),a.x+=c.x-f.x,a.y+=c.y-f.y,f={x:c.x,y:c.y},a.triggerRedraw())},listenerId:a.id});a.events.addEventListener({eventGroupType:"movable",eventId:"pointerUp",handleEvent:function(c){!d||e&&e()||(a.controller.log("End detected for touch "+a.touchIdentifier),a.controller.getCanvasXYFromClientXY(c),a.x+=c.x-f.x,a.y+=c.y-f.y,a.moveCompleted(c),a.touchIdentifier=null,b=!1,a.triggerRedraw())},listenerId:a.id})}})})();CreJs=CreJs||{};
(function(){CreJs.Creanvas=CreJs.Creanvas||{};CreJs.Creanvas.elementDecorators=CreJs.Creanvas.elementDecorators||[];CreJs.Creanvas.elementDecorators.push({type:"moving",applyTo:function(a,c){var d,f,e,b,g,h,k,l;a.moving=a.moving||{};a.moving.speed=new CreJs.Core.Vector(c.vx||0,c.vy||0);a.moving.acceleration=new CreJs.Core.Vector(c.ax||0,c.ay||0);a.moving.rotationSpeed=c.omega||0;h=a.controller.getTime();setInterval(function(){k=a.controller.getTime();l=k-h;if(!(1>l)&&(h=k,a.moving.speed.x+=a.moving.acceleration.x*
l,a.moving.speed.y+=a.moving.acceleration.y*l,0!=a.moving.speed.x||0!=a.moving.speed.y||0!=a.moving.rotationSpeed||a.scaleSpeed&&(0!=a.scaleSpeed.x||0!=a.scaleSpeed.y))){d=a.x;f=a.y;e=a.angle;b=a.scaleX;g=a.scaleY;a.x+=a.moving.speed.x*l;a.y+=a.moving.speed.y*l;a.angle+=a.moving.rotationSpeed*l;a.scaleSpeed&&(a.scaleX+=a.scaleSpeed.x*l,a.scaleY+=a.scaleSpeed.y*l);var c=!0;a.preMove&&a.preMove.forEach(function(b){c&&(b.call(a)||(c=!1))});c||(a.x=d,a.y=f,a.angle=e,a.scaleX=b,a.scaleY=g)}},20)}})})();CreJs=CreJs||{};
(function(){var a;(CreJs.Creevents=CreJs.Creevents||{}).Event=function(c){this.eventId=c;a=CreJs.CreHelpers;var d=[],f=new CreJs.Crelog.Logger;this.dispatch=function(e,b){var g=a.GetGuid(),h=d.length;e&&"pointerMove"!=e.eventId&&"drag"!=e.eventId&&"drop"!=e.eventId&&f.log("Dispatching "+h+" "+e.eventId+". ("+g+")");d.forEach(function(a){a.debugEvent=c;setTimeout(function(){e&&"pointerMove"!=e.eventId&&"drag"!=e.eventId&&"drop"!=e.eventId&&f.log("Actually handling "+e.eventId+". ("+g+")");a.handleEvent(e);
h--;0==h&&b&&b()})})};this.addEventListener=function(c){var b=a.GetGuid();d.push({handlerGuid:b,handleEvent:c.handleEvent,rank:c.rank,listenerId:c.listenerId,eventGroupType:c.eventGroupType});d=d.sort(function(a,b){return(a.rank||Infinity)-(b.rank||Infinity)});return b};this.removeEventListener=function(a){d=d.filter(function(b){return Boolean(a.handlerGuid)&&b.handlerGuid!=a.handlerGuid||Boolean(a.listenerId)&&b.listenerId!=a.listenerId||Boolean(a.eventGroupType)&&b.eventGroupType!=a.eventGroupType})}}})();CreJs=CreJs||{};
(function(){var a=CreJs.Creevents=CreJs.Creevents||{};a.EventContainer=function(){var c=this,d={},f=[];this.hasEvent=function(a){return void 0!=d[a]};var e=function(b){f.push(b);d[b]=new a.Event(b)};this.addEventListener=function(a){d[a.eventId]||e(a.eventId);return d[a.eventId].addEventListener(a)};this.dispatch=function(a,c,e){d[a]&&(c&&(c.eventId=a),d[a].dispatch(c,e))};this.removeEventListener=function(a){d[a.eventId]?d[a.eventId].removeEventListener(a):f.forEach(function(c){d[c].removeEventListener(a)})};this.registerControlEvent=
function(a,f,h){d[h]||e(h);a.addEventListener(f,function(a){a.preventDefault();setTimeout(function(){c.dispatch(h,a)},0)})}}})();CreJs=CreJs||{};(function(){var a=CreJs.CreHelpers=CreJs.CreHelpers||{};a.GetGuid=function(){var c=Date.now().toString(16),c=a.repeatString("x",15-c.length)+c;return("xxxxxxxx-xxxx-4xxx-y"+c.slice(0,3)+"-"+c.slice(3)).replace(/[xy]/g,function(a){var c=16*Math.random()|0;return("x"==a?c:c&3|8).toString(16)})};a.repeatString=function(c,d){return 0>=d?"":c+a.repeatString(c,d-1)}})();CreJs=CreJs||{};(function(){(CreJs.Crelog=CreJs.Crelog||{}).Logger=function(){this.log=function(a){}}})();
